apply from: '../../constants.gradle'
apply plugin: 'com.android.library'

android {
    compileSdkVersion project.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion project.ext.minSdkVersion
        targetSdkVersion project.ext.targetSdkVersion
        consumerProguardFiles 'proguard-rules.txt'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    sourceSets.main {
        jniLibs.srcDirs = ['src/main/jniLibs', 'src/main/libs']
        jni.srcDirs = [] // Disable automatic native build if using prebuilt libs
    }

    testOptions.unitTests.includeAndroidResources = true
}

// Optionally configure cmake if dav1d source is present
if (project.file('src/main/jni/dav1d').exists() && System.getenv('NDK_PATH') != null) {
    android.externalNativeBuild {
        cmake {
            path file('src/main/jni/CMakeLists.txt')
        }
    }
}

dependencies {
    implementation project(modulePrefix + 'library-core')
    implementation 'androidx.annotation:annotation:1.1.0'
    testImplementation project(modulePrefix + 'testutils-robolectric')
    androidTestImplementation 'androidx.test:runner:' + androidXTestVersion
    androidTestImplementation 'androidx.test.ext:junit:' + androidXTestVersion
    androidTestImplementation 'androidx.test.ext:truth:' + androidXTestVersion
}

ext {
    javadocTitle = 'DAV1D extension'
}
